#!/bin/bash

##############################################
# Build Script: Combine Modular Files
##############################################
# This script combines all modular CSS and JS files
# into single combined files for production use.
#
# Usage:
#   chmod +x build-combined.sh
#   ./build-combined.sh
#
# Output:
#   - quiz-combined.css (all CSS modules)
#   - quiz-master-app-combined.js (all JS modules)
##############################################

echo "🔨 Building combined files..."
echo ""

# Check if css/ directory exists
if [ ! -d "css" ]; then
    echo "❌ Error: css/ directory not found!"
    exit 1
fi

# Check if js/ directory exists
if [ ! -d "js" ]; then
    echo "❌ Error: js/ directory not found!"
    exit 1
fi

##############################################
# Combine CSS Files
##############################################
echo "📦 Combining CSS files..."

cat > quiz-combined.css << 'EOF'
/**
 * COMBINED QUIZ CSS
 * ===========================================
 * This file is AUTO-GENERATED from modular CSS files.
 * DO NOT EDIT THIS FILE DIRECTLY!
 *
 * Edit individual files in css/ folder, then run:
 * ./build-combined.sh
 *
 * Generated on: $(date)
 */

EOF

# Combine all CSS modules in correct order
cat css/base-reset.css \
    css/bubble-animations.css \
    css/layout-container.css \
    css/home-page.css \
    css/cards.css \
    css/buttons.css \
    css/quiz.css \
    css/progress-results.css \
    css/collapsible.css \
    css/topics-badges.css \
    css/emojis-effects.css \
    css/mobile-responsive.css \
    >> quiz-combined.css

echo "✅ quiz-combined.css created ($(wc -l < quiz-combined.css) lines)"

##############################################
# Combine JavaScript Files
##############################################
echo "📦 Combining JavaScript files..."

cat > quiz-master-app-combined.js << 'EOF'
/**
 * COMBINED QUIZ MASTER APP
 * ===========================================
 * This file is AUTO-GENERATED from modular JS files.
 * DO NOT EDIT THIS FILE DIRECTLY!
 *
 * Edit individual files in js/ folder, then run:
 * ./build-combined.sh
 *
 * IMPORTANT: Load order matters!
 * Generated on: $(date)
 */

EOF

# Combine all JS modules in correct order
cat js/quiz-state.js \
    js/quiz-storage.js \
    js/quiz-data.js \
    js/quiz-timer.js \
    js/quiz-animations.js \
    js/quiz-display.js \
    js/quiz-logic.js \
    js/quiz-results.js \
    js/quiz-navigation.js \
    js/quiz-init.js \
    >> quiz-master-app-combined.js

echo "✅ quiz-master-app-combined.js created ($(wc -l < quiz-master-app-combined.js) lines)"

##############################################
# Summary
##############################################
echo ""
echo "🎉 Build complete!"
echo ""
echo "Generated files:"
echo "  - quiz-combined.css"
echo "  - quiz-master-app-combined.js"
echo ""
echo "Next steps:"
echo "  1. Copy these files to production branch"
echo "  2. Rename quiz-combined.css → quiz.css"
echo "  3. Rename quiz-master-app-combined.js → quiz-master-app.js"
echo "  4. Update WPCode snippets if needed"
echo ""
